### ISSUE TITLE
Version 2.8.6 not found in node 0.10

### ISSUE THREAD

**Issue by tunnckoCore** [commitizen/cz-cli#382]
Actually I don't care so much about node 0.10, but something is messed and wrong with that package.

In travis, highest version available is 2.8.1, so.. Node 0.10 is dropped without semantic versioning or what?
There's no changelog too.

And finally, is there any quick fix for that? Which is latest version available for node 0.10. Because Im using commitizen in my latest packages from last two-three months, and builds are failing because such devDeps. In some cases in some packages I need and want to support node 0.10 for few more months.

In anyway, it's not so big problem, cuz my travis configs "allow_failures" on 0.10, 0.12 and 4, and most builds pass, but in some of my packages I force all versions.

```yaml
sudo: false
language: node_js

node_js:
  - "node"
  - "6"
  - "4"
  - "0.12"
  - "0.10"

notifications:
  email: false

after_success: npm run report-coverage
```

and my default config for most packages is 

```yaml
sudo: false
language: node_js

node_js:
  - "node"
  - "6"
  - "4"
  - "0.12"
  - "0.10"

matrix:
  fast_finish: true
  allow_failures:
    - node_js: "4"
    - node_js: "0.12"
    - node_js: "0.10"

notifications:
  email: false

after_success: npm run report-coverage

```

So, again, what version should I lock?

***

edit: travis failing with

```
The command "eval npm install " failed. Retrying, 2 of 3.
npm ERR! Linux 3.13.0-40-generic
npm ERR! argv "/home/travis/.nvm/v0.10.48/bin/node" "/home/travis/.nvm/v0.10.48/bin/npm" "install"
npm ERR! node v0.10.48
npm ERR! npm  v2.15.1
npm ERR! code ETARGET
npm ERR! notarget No compatible version found: commitizen@'>=2.8.6 <3.0.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["1.0.1","1.0.2","1.0.3","1.0.4","1.0.5","2.0.0","2.0.1","2.0.2","2.1.0","2.2.0","2.2.1","2.3.0","2.4.0","2.4.1","2.4.2","2.4.3","2.4.4","2.4.5","2.4.6","2.5.0","2.5.1","2.6.0","2.6.1","2.6.2","2.6.3","2.7.0","2.7.1","2.7.2","2.7.3","2.7.4","2.7.5","2.7.6","2.8.0","2.8.1"]
```
