### ISSUE TITLE
Add `pre-commit` hook that will run Commitizen on `git commit`

### ISSUE THREAD

**Issue by ShaneKosieradzki** [commitizen/cz-cli#801]
## Background
[pre-commit](https://pre-commit.com/index.html) is a package manager for git hooks. The project allows hooks to be downloaded locally and run in an isolated environment. This allows for easy adoption of hooks written in a variety of languages and allows for quick adoption by contributors who are unfamiliar with any particular hook.

## Possible Solution
This project can make itself `pre-commit` compatible by adding a `.pre-commit-hooks.yaml` file.  You can use this file to make your existing `prepare-commit-msg ` hook and the Commitizen project as a whole more accessible.

**Comment by paulmboyce** [comment]
Hi @ShaneKosieradzki , if it helps, you can use husky to run pre commit hooks.

Install husky:

`npm install--save-dev husky
`

Then run this to add a pre commit message hook:

`npx husky add .husky/prepare-commit-msg "exec < /dev/tty && git cz --hook || true"
`

Note, you will probably want to add the resulting hook file to git:

`
.husky/prepare-commit-msg
`

I know that isn't enhancing commitizen itself, but it does get you the pre commit hooks 

Hope that helps!

**Comment by offbyone** [comment]
That doesn't help if a team already has hooks written for `pre-commit` -- it would be nice to be able to share the same rules and commit message checking here.

**Comment by donhector** [comment]
Try with this hook

```yaml
- repo: https://github.com/commitizen-tools/commitizen
  rev: master
  hooks:
    - id: commitizen
      stages: [commit-msg]
```
Or create your own local hook in `.pre-commit-config.yaml` that calls commitizen. I generally wrap the call in a make target, so the hook's entry is something like 'make commitizen' and the language is `system`

**Comment by lays147** [comment]
@donhector I'm trying to use your hook, and it's failing because `cz` is receiving the list of my staged files instead of the `check` argument.
```sh
commitizen check.........................................................Failed
- hook id: commitizen
- exit code: 13

usage: cz
       [-h]
       [--debug]
       [-n NAME]
       {init,commit,c,ls,example,info,schema,bump,changelog,ch,check,version}
       ...
cz: error: unrecognized arguments: settings.toml Dockerfile .dockerignore Template/config.py .editorconfig .gitignore pyproject.toml tests/conftest.py poetry.lock .pre-commit-config.yaml .github/workflows/python.yml tox.ini README.md Template/logging/__init__.py
Command is required
```

Any tips on how to fix it? Do I need to add any arguments? 

Thanks

**Comment by donhector** [comment]
> @donhector I'm trying to use your hook, and it's failing because `cz` is receiving the list of my staged files instead of the `check` argument.
> 
> ```shell
> commitizen check.........................................................Failed
> - hook id: commitizen
> - exit code: 13
> 
> usage: cz
>        [-h]
>        [--debug]
>        [-n NAME]
>        {init,commit,c,ls,example,info,schema,bump,changelog,ch,check,version}
>        ...
> cz: error: unrecognized arguments: settings.toml Dockerfile .dockerignore Template/config.py .editorconfig .gitignore pyproject.toml tests/conftest.py poetry.lock .pre-commit-config.yaml .github/workflows/python.yml tox.ini README.md Template/logging/__init__.py
> Command is required
> ```
> 
> Any tips on how to fix it? Do I need to add any arguments?
> 
> Thanks

Could you share your `.pre-commit-config.yaml` file?

**Comment by lays147** [comment]
@donhector 
```yml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: check-docstring-first
      - id: detect-aws-credentials

  - repo: https://github.com/pre-commit/pygrep-hooks 
    rev: v1.9.0 
    hooks:
      - id: python-check-mock-methods
      - id: python-use-type-annotations

  - repo: https://github.com/hadolint/hadolint
    rev: master
    hooks:
      - id: hadolint-docker

  - repo: local
    hooks:
    - id: lint and format
      name: Lint and format files
      entry: poetry run tox -e lint
      language: system
    - id: compliance and quality
      name: Run for compliance and quality checks
      entry: poetry run tox -e compliance
      language: system
  
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.20.0
    hooks:
      - id: commitizen
    stages: [commit-msg]
```

**Comment by donhector** [comment]
@lays147 You `stages: [commit-msg]` indentation looks incorrect. Should be like this:

```
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.20.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
```
