### ISSUE TITLE
How to skip cz-cli prompt

### ISSUE THREAD

**Issue by kiril-daskalov** [commitizen/cz-cli#859]
How can I skip/prevent  prompt if I want?

My release pipeline stuck because I can't skip the prompt.

**Comment by marcitqualab** [comment]
Ctrl + C works for me

**Comment by runkecheng** [comment]
I have the same problem, when input the information, it will prompt the previous input.

**Comment by ilmeskio** [comment]
don't know if it can be still helpful after all this time. I am using cli agents and they are of course not working properly with the interactive part but I found really helpful to have cz-cli. I am using lefthook in the prepare-commit-msg hook to have the prompt in my human developer experience. 

I found to skip the hook by checking an environment variable: I choose CI cause it can be helpful also for other scripts and maybe was @kiril-daskalov case.

```yaml
prepare-commit-msg:
  # Lefthook’s skip directive lets us exit early when CI=1 (see https://lefthook.dev/examples/skip.html), so release bots or scripted commits can bypass the wizard cleanly.
  skip:
    - run: test "${CI:-0}" = "1"
  jobs:
    - name: commitizen
      interactive: true
      env:
        LEFTHOOK: 0
      run: pnpm commit --hook
```
