### ISSUE TITLE
bump command doesn't create tags

### ISSUE THREAD

**Issue by 12rambau** [commitizen/cz-cli#885]
I want to use the commitizen librairy in my Python project: https://github.com/ESA-PhiLab/OpenSarToolkit. 

As repository with a default branch called "main" are not yet covered by the github action, I'd like to go back to the good old CLI option. 

With the following `.cz.yaml`:
```yaml
commitizen:
  changelog_file: CHANGELOG.md
  update_changelog_on_bump: true
  name: cz_conventional_commits
  tag_format: $major.$minor.$patch$prerelease
  version: 0.12.6
  version_files:
  - setup.py:version
  - ost/__init__.py:__version__
```

running the following command: 
```
cz bump 
```

I would expect cz to: 
- update the version number  
- commit the bump 
- create a tag
- update the changelog

But the tag is not created. instead I get the following: 
```
bump: version 0.12.5 → 0.12.6
tag to create: 0.12.6
increment detected: PATCH
```

meaning that my bump is undetected by changelog leading to this file: 
```md
## Unreleased

### Refactor

- drop useless with_suffix
- drop usage of joinpath
- lint
- compliant with PEP and Black
```

Is it normal ? how can I create the tag using the CLI ?
