### ISSUE TITLE
[skip-ci] generates an invalid commit message

### ISSUE THREAD

**Issue by tkschmidt** [commitizen/cz-cli#999]
Hey *,
I've prepared an internal repository to enable the provided gitlab-ci template. The [manual](https://commitizen-tools.github.io/commitizen/tutorials/gitlab_ci/) states that `The commit message executed automatically by the CI must include [skip-ci] `

I have done so via the [provided example](https://commitizen-tools.github.io/commitizen/commands/bump/#bump_message).

So my `.cz.toml` looks like
```toml
[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "semver"
version_provider = "cargo"
update_changelog_on_bump = true
major_version_zero = true
bump_message = "release $current_version → $new_version [skip-ci]"
```

If I run now locally (or within the CI) `cz bump`, it shows me the following error message:

```
release 0.5.0 → 0.6.0 [skip-ci]
tag to create: 0.6.0
increment detected: MINOR

2nd git.commit error: "commitizen check.........................................................Failed
- hook id: commitizen
- exit code: 14

commit validation: failed!
please enter a commit message in the commitizen format.
commit "": "release 0.5.0 → 0.6.0 [skip-ci]"
pattern: (?s)(build|ci|docs|feat|fix|perf|refactor|style|test|chore|revert|bump)(\(\S+\))?!?:( [^\n\r]+)((\n\n.*)|(\s*))?$"
```

What am I doing wrong?

Best,
Tobi
